inventory/urls.py
from django.urls import path,include
from . import views


urlpatterns =[
    path('', views.home, name='home'),
    path('add_product', views.addproduct_view, name='addproduct'),
    path('customer/<str:cust_id>', views.customer_view, name='customer'),
    path('add_order',views.add_order,name='add_order'),
    path('update_order/<str:order_id>',views.update_order,name='update_order'),
    path('add_customer',views.addcustomer,name='add_customer'),
    
    
    path('test', views.test_view, name='test'),
    ]

simpleinventory/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
    path("select2/", include("django_select2.urls"))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

inventory/models.py
from django.db import models
import datetime
from decimal import *


# Create your models here.
def currencyInIndiaFormat(n):
  d =n 
  if d.as_tuple().exponent < -2:
    s = str(n)
  else:
    s = '{0:.2f}'.format(n)
  l = len(s)
  i = l-1;
  res = ''
  flag = 0
  k = 0
  while i>=0:
    if flag==0:
      res = res + s[i]
      if s[i]=='.':
        flag = 1
    elif flag==1:
      k = k + 1
      res = res + s[i]
      if k==3 and i-1>=0:
        res = res + ','
        flag = 2
        k = 0
    else:
      k = k + 1
      res = res + s[i]
      if k==2 and i-1>=0:
        res = res + ','
        flag = 2
        k = 0
    i = i - 1

  return res[::-1]


class Customer(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    mobile_no = models.CharField(max_length=10)
    email = models.EmailField()
    registered_on = models.DateTimeField(auto_now_add=True,blank=True)

    def __str__(self):
        return self.name


class Vendor(models.Model):

  name= models.CharField(max_length=50)
  address = models.CharField(max_length=100)
  mobile_no = models.CharField(max_length=10)
  email= models.EmailField()
  registered_on = models.DateTimeField(auto_now_add=True,blank=True)

  def __str__(self):
      return self.name

  


class ProductCategory(models.Model):

    category_name = models.CharField(max_length=30)
    labor_charge = models.DecimalField(max_digits=10,decimal_places=2)

    def __str__(self):
        return self.category_name + ' , '+ str(self.labor_charge)
    
    class Meta:
        verbose_name_plural = "Product Categories"



class ProductType(models.Model):
    type = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=10,decimal_places=2, null=True)



    def __str__(self):
        return self.type + ' , '+ str(self.price)
    class Meta:
        verbose_name_plural = "Product Types"


class Product(models.Model):

    title = models.CharField(max_length=30)
    category = models.ForeignKey('ProductCategory',on_delete= models.CASCADE)
    type = models.ForeignKey('ProductType',on_delete = models.CASCADE)
    weight = models.DecimalField(max_digits=10,decimal_places=3 ,default=0) #weight in gram
    jarti = models.DecimalField(max_digits=10,decimal_places=3,default=0)
    vendor = models.ForeignKey('Vendor',on_delete=models.SET_NULL,null=True)
    image = models.ImageField(null=True,default='imageplaceholder.jpg')
    added = models.DateTimeField(auto_now_add=True,blank=True)
    

    def __str__(self):
        return self.title
    
    

    def getprice(self):
        latest_price = ((self.weight + self.jarti)*self.type.price)/Decimal(11.66) + self.category.labor_charge
        # return round(latest_price,ndigits=0)
        return currencyInIndiaFormat(
            round(latest_price,ndigits=2)
            )
    
    getprice.short_description = 'Price'

    def getvendor(self):
        # vendor_get= self.purchasefromvendor_set.last()
        # vendor_name = vendor_get
        # print(vendor_name)
        # return vendor_name
        vendor = self.vendor
        return vendor
    
    getvendor.short_description = 'Vendor'

class PurchaseFromVendor(models.Model):
  order_id = models.CharField(max_length=20)
  vendor = models.ForeignKey(Vendor,on_delete=models.SET_NULL,null=True,blank=True)
  product = models.ManyToManyField(Product)
  order_date = models.DateTimeField()

  def __str__(self):
      return self.order_id + ' '+ str(self.vendor)

ORDER_STATUS_CHOICES =[

    ('pending', 'Pending'),
    ('processing', 'Processing'),
    ('canceled', 'Cancelled'),
    ('completed', 'Completed'),
    ('onhold', 'OnHold'),

]

class Order(models.Model):
  product = models.ManyToManyField(Product)
  customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null=True)
  date_ordered= models.DateTimeField(auto_now_add=True)
  order_status = models.CharField(choices=ORDER_STATUS_CHOICES,max_length=30,default='pending')
  notes = models.CharField(max_length=100)

  def __str__(self):
    return str(self.id)
  



  

inventory/forms.py
from django import forms
from .models import Product, Order,Customer
from django_select2 import forms as s2forms


class Products(s2forms.ModelSelect2MultipleWidget):
    search_fields = [
        'title__icontain'
    ]

class Customers(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontain",
        "mobile_no__icontain"
    ]



class ProductCreationForm(forms.ModelForm):
    
    class Meta:
        model = Product
        fields = '__all__'

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'

inventory/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from .models import *
from .forms import ProductCreationForm, OrderForm, CustomerForm


def home(request):
    products = Product.objects.all()
    order = Order.objects.all()
    order_count = Order.objects.all().count()
    order_completed = Order.objects.filter(order_status='completed').count()
    order_pending = Order.objects.filter(order_status='pending').count()
    customers = Customer.objects.all()
    customer_count = customers.count()
    
    orderform = OrderForm()
    if request.method == 'POST':
        orderform = OrderForm(request.POST)
        if orderform.is_valid():
            orderform.save()
            return redirect('/')
    
    context = {
        'products': products,
        'orders':order,
        'order_count':order_count,
        'order_completed':order_completed,
        'order_pending':order_pending,
        'customers':customers,
        'customer_count':customer_count,
        'orderform':orderform,
        
    }

    return render(request,'inventory/dashboard.html',context)

def add_order(request):
    orderform = OrderForm()
    if request.method == 'POST':
        orderform = OrderForm(request.POST)
        if orderform.is_valid():
            orderform.save()
            return redirect('/')
    context = {
        'orderform': orderform,
    }
    return render(request, 'inventory/customerorder.html',context)

def update_order(request,order_id):
    order = Order.objects.get(id=order_id)
    orderform = OrderForm(instance = order)
    if request.method == 'POST':
        orderform = OrderForm(request.POST,instance= order)
        if orderform.is_valid():
            orderform.save()
            return redirect('/')
    context = {
        'orderform':orderform
    }
    return render(request,'inventory/updateorder.html',context)


def addproduct_view(request):
    if request.user.is_authenticated:
        print('user is :'+str(request.user))

        product_form = ProductCreationForm()
        if request.method == 'POST':
            product_form = ProductCreationForm(request.POST)
            if product_form.is_valid():
                product_form.save()
                return redirect('/')
        context = {'form': product_form}
        return render(request,'inventory/products.html',context )
    return redirect('/')

def addcustomer(request):
    customerform = CustomerForm()
    context = {
        'customerform':customerform,
    }
    return render(request, 'inventory/addcustomer.html',context)

def customer_view(request,cust_id):
    customer = Customer.objects.get(pk=cust_id)
    order = customer.order_set.all()
    orderk = customer.order_set.all()
    for orderkk in orderk:
        print(orderkk.order_status)
        for order_items in orderkk.product.all():
            print(order_items.title)
            print(order_items.getprice()) 
        
    order_count = order.count()
    data = {
        'customer': customer,
        'order': order,
        'order_count':order_count
    }
    return render(request,'inventory/customer.html',data)

def test_view(request):
    return render(request,'inventory/test.html')

inventory/templates/inventory/401.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>404 Error - SB Admin</title>
        <link href="css/styles.css" rel="stylesheet" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>
    </head>
    <body>
        <div id="layoutError">
            <div id="layoutError_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-6">
                                <div class="text-center mt-4">
                                    <h1 class="display-1">401</h1>
                                    <p class="lead">Unauthorized</p>
                                    <p>Access to this resource is denied.</p>
                                    <a href="index.html"><i class="fas fa-arrow-left mr-1"></i>Return to Dashboard</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
            <div id="layoutError_footer">
                <footer class="py-4 bg-light mt-auto">
                    <div class="container-fluid">
                        <div class="d-flex align-items-center justify-content-between small">
                            <div class="text-muted">Copyright &copy; Your Website 2019</div>
                            <div>
                                <a href="#">Privacy Policy</a>
                                &middot;
                                <a href="#">Terms &amp; Conditions</a>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
        <script src="js/scripts.js"></script>
    </body>
</html>

inventory/templates/inventory/addcustomer.html
{%extends 'inventory/base.html'%}
{%load static%}

{%block content%}
Customer Creation Page
<form action="" method="post">
    {% csrf_token%}
    {{customerform.as_p}}
    <input type="submit" value="Add Customer">
</form>

{%endblock%}

inventory/templates/inventory/base.html
<!DOCTYPE html>
<html lang="en">
{%load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark  mb-3">
        <a class="navbar-brand" href="{% url 'home'%}">SIMPLE INVENTORY</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Dashboard <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Add Product</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'add_order' %}" class="nav-link">Add Order</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Billing</a>
            </li>
          </ul>
        </div>
      </nav>

    {%block content%}
    {%endblock content%}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script>
    $(document).ready(function() {
      $('#id_product').select2();
      $('#id_customer').select2();
  });
  </script>
  </body>
</html>

inventory/templates/inventory/customer.html
{%extends 'inventory/base.html'%}


{% block content %}

<div class="container-fluid">


<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<h5>Customer: {{customer.name}}</h5>
			<hr>
			<a class="btn btn-outline-info  btn-sm btn-block" href="">Update Customer</a>
			<a class="btn btn-outline-danger  btn-sm btn-block" href="">Delete Customer</a>

		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Contact Information</h5>
			<hr>
			<p><strong>Email: </strong>{{customer.email}}</p>
			<p><strong>Phone:</strong> {{customer.mobile_no}}</p>
			<p><strong>Address:</strong> {{customer.address}}</p>
			<p><strong>Registered:</strong> {{customer.registered_on}}</p>
		</div>
	</div>

	<div class="col-md">
		<div class="card card-body">
			<h5>Total Orders</h5>
			<hr>
			<h1 style="text-align: center;padding: 10px">{{order_count}}</h1>
		</div>
	</div>
</div>


<br>
<div class="row">
	<div class="col">
		<div class="card card-body">
			<form method="get">

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
		</div>
	</div>
	
</div>
<br>

<div class="row">
	<div class="col-md">
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Notes</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
				{%for order in order%}
				<tr>	
					<!-- <td>
					{%for orderitem in order.product.all%}
						{{orderitem.title}},
					{%endfor%}

					</td>
						
					<td>
						{%for orderitem in order.product.all%}
							{{orderitem.category}}
						{%endfor%}
	
						</td> -->
						<!-- <td>
							
						</td> -->
					<td>
					
							{%for orderitem in order.product.all%}
								<!-- <tr>
								<td>{{orderitem.title}}</td>
								<td>{{orderitem.category.category_name}}</td>
								</tr> -->

								<div class="card " style="width: 30em;">
									<div class="row">
										<div class="col">
											<img class="card-img-top" src="{{orderitem.image.url}}" alt="Card image cap">
										</div>
										<div class="col">
											
											  <ul class="list-group list-group-flush">
												<li class="list-group-item"><strong>
													{{orderitem.title}}
												</strong></li>
												<li class="list-group-item"><strong>Weight :</strong>{{orderitem.weight}}</li>
												<li class="list-group-item"><strong>Category :</strong>{{orderitem.category.category_name}}</li>
												<li class="list-group-item"><strong>Price :</strong> Rs {{orderitem.getprice}}</li>
											
											  </ul>
										</div>
									</div>
									<!-- <div class="card-body">
									  <a href="#" class="card-link">Card link</a>
									  <a href="#" class="card-link">Another link</a>
									</div> -->
								  </div>
							{%endfor%}
					
					</td>
					<td>{{order.notes}}</td>
					<td>{{order.date_ordered}}</td>
					{%if order.order_status == "completed" %}
						<td>
							<span class="badge badge-success">Completed</span>
						</td>
					{%endif%}
					{%if order.order_status == "processing" %}
						<td>
							<span class="badge badge-primary">Processing</span>
						</td>
					{%endif%}
					{%if order.order_status == "pending" %}
						<td>
							<span class="badge badge-dark">Pending</span>
						</td>
					{%endif%}
					{%if order.order_status == "canceled" %}
						<td>
							<span class="badge badge-danger">Cancelled</span>
						</td>
					{%endif%}
					{%if order.order_status == "onhold" %}
						<td>
							<span class="badge badge-warning">OnHold</span>
						</td>
					{%endif%}
					<td><a href="{% url 'update_order' order.id %}">
						<span class="badge badge-primary">Update</span>

					</a>
					</td>
					<td>remove</td>
					
				</tr>
				{%endfor%}


			</table>
		</div>
	</div>
</div>
</div>

{%endblock content %}

inventory/templates/inventory/customerorder.html
{%extends 'inventory/base.html'%}
{%load static %}


{%block content%}
<div class="container">


<div class="card col-lg-6 justify-content-center ">
    <div class="card-body">
        <form action="" method="post">
            {% csrf_token %}
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                   <strong>Product: </strong> {{orderform.product}}
                </li>
                <li class="list-group-item">
                    <strong>Customer: </strong> {{orderform.customer}}
                 </li>
                 <li class="list-group-item">
                    <strong>Order Status: </strong> {{orderform.order_status}}
                 </li>
                 <li class="list-group-item">
                    <strong>Notes: </strong> {{orderform.notes}}
                 </li>
            </ul>
            {{form.media.js}}
            <input type="submit" value="Add Order">
        </form>

    </div>
    

</div>
</div>




{%endblock%}

inventory/templates/inventory/dashboard.html
{% extends 'inventory/base.html' %}
{%load static %}

{%block content%}
{%include 'inventory/status.html'%}
<br>
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
	Add Customer
  </button>
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addorder">
	Add Order
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="addorder" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog" role="document">
	  <div class="modal-content">
		<div class="modal-header">
		  <h5 class="modal-title" id="exampleModalLabel">Add Order</h5>
		  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		  </button>
		</div>
		<form action="/add_order" method="post">
			<div class="modal-body">

				{% csrf_token %}
            <div class="form-group">
				<strong>Product: </strong> {{orderform.product}}
			</div>
            <div class="form-group">
				<strong>Customer: </strong> {{orderform.customer}}
			</div>
			<div class="form-group">
				<strong>Order Status: </strong> {{orderform.order_status}}
			</div>
            <div class="form-group">
				<strong>Notes: </strong> {{orderform.notes}}
			</div>
                
        
            {{form.media.js}}
			  </div>
			  <div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
				<button type="submit" class="btn btn-primary">Add Order</button>
			  </div>

		</form>
		
	  </div>
	</div>
  </div>
<div class="container-fluid">


<div class="row">
	<div class="col-md-5">
		<h5>CUSTOMERS: <strong>{{customer_count}}</strong></h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'add_customer' %}">Create Customer</a>
			<table class="table table-sm">
				<tr>
					<th></th>
					<th>Customer</th>
					<th>Orders</th>
				</tr>
				{%for customer in customers %}
				<tr>
					<td>
						<a href="{% url 'customer' customer.id %}" class="btn btn-sm btn-info">View</a>
						
					</td>
					<td>{{customer.name}}</td>
					<td>{{customer.order_set.all.count}}</td>
				</tr>
				{%endfor%}

			</table>
		</div>
	</div>

	<div class="col-md-7">
		<h5>LAST 5 ORDERS</h5>
		<hr>
		<div class="card card-body">
			<a class="btn btn-primary  btn-sm btn-block" href="{% url 'add_order'%}">Create Order</a>
			<table class="table table-sm">
				<tr>
					<th>Product</th>
					<th>Date Orderd</th>
					<th>Status</th>
					<th>Update</th>
					<th>Remove</th>
				</tr>
				{%for order in orders%}
				<tr>

					<td>{{order.notes}}</td>
					<td>{{order.date_ordered}}</td>
					<td>{{order.order_status}}</td>
				</tr>
					
				{%endfor%}
		
			</table>
		</div>
	</div>

</div>
</div>

            {%endblock content%}
           

inventory/templates/inventory/products.html
{%extends 'inventory/base.html'%}



{%block content%}
This is Products section
<form action="" method="POST">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Add Product">
</form>

{%endblock content%}

inventory/templates/inventory/status.html
<br>
<div class="container-fluid">
	<div class="row">
		<div class="col">
			<div class="col-md">
				<div class="card text-center text-white  mb-3" id="total-orders">
					<div class="card-header">
						<h5 class="card-title">Total Orders</h5>
					</div>
					<div class="card-body">
						<h3 class="card-title">{{order_count}}</h3>
					</div>
				</div>
			</div>
		</div>

		<div class="col">
			<div class="col-md">
				<div class="card text-center text-white  mb-3" id="orders-delivered">
					<div class="card-header">
						<h5 class="card-title">Orders Delivered</h5>
					</div>
					<div class="card-body">
						<h3 class="card-title">{{order_completed}}</h3>
					</div>
				</div>
			</div>
		</div>

		<div class="col">
			<div class="col-md">
				<div class="card text-center text-white  mb-3" id="orders-pending">
					<div class="card-header">
						<h5 class="card-title">Orders Pending</h5>
					</div>
					<div class="card-body">
						<h3 class="card-title">{{order_pending}}</h3>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

inventory/templates/inventory/test.html
{%extends 'inventory/base.html' %}



{%block content%}

<!-- 
{% include 'inventory/status.html' %} -->


<div class="container-fluid">
    <div class="row">
        <div class="col-md">
              <div class="card text-center text-white  mb-3" id="total-orders" >
                  <div class="card-header">
                      <div class="card-title">
                          <h5>Total</h5>
                      </div>
                  </div>
                  <div class="body">
                      <div class="card-title">
                          <h3>22</h3>
                      </div>
                  </div>
              </div>
        </div>
        <div class="col-md">
            <div class="card text-center text-white  mb-3" id="total-orders" >
                <div class="card-header">
                    <div class="card-title">
                        <h5>Total</h5>
                    </div>
                </div>
                <div class="body">
                    <div class="card-title">
                        <h3>22</h3>
                    </div>
                </div>
            </div>
      </div>
      <div class="col-md">
        <div class="card text-center text-white  mb-3" id="total-orders" >
            <div class="card-header">
                <div class="card-title">
                    <h5>Total</h5>
                </div>
            </div>
            <div class="body">
                <div class="card-title">
                    <h3>22</h3>
                </div>
            </div>
        </div>
  </div>   
        </div>
      </div>


</div>
    
  

{%endblock content%}

inventory/templates/inventory/updateorder.html
{%extends 'inventory/base.html'%}
{%load static%}

{%block content%}
<form action="" method="post">
    {%csrf_token%}
{{orderform.as_p}}
<input type="submit" value="Update Order">
</form>
{%endblock content%}